module.exports = {
 content: ['./**/*.php'],
 theme: {
  container: {
   center: true,
   padding: {
    DEFAULT: '1rem',
    sm: '2rem',
    lg: '4rem',
    xl: '5rem',
    '2xl': '6rem',
   },
  },
 },
 plugins: [require('@tailwindcss/typography'), require('@tailwindcss/forms')],
 safelist: [
  'text-white',
  'bg-blue-700',
  'hover:bg-blue-800',
  'focus:ring-4',
  'focus:ring-blue-300',
  'font-medium',
  'rounded-lg',
  'text-sm',
  'px-5',
  'py-2.5',
  'pb-2.5',
  'pt-2',
  'dark:bg-blue-600',
  'dark:hover:bg-blue-700',
  'focus:outline-none',
  'dark:focus:ring-blue-800',
  'mb-5',
  'text-center',
 ],
};
